insert into "rbac_permissions" ("action", "description", "id", "module_id") values ('create', 'Customer 360 â€” create', 1, 1);
insert into "rbac_permissions" ("action", "description", "id", "module_id") values ('read', 'Customer 360 â€” read', 2, 1);
insert into "rbac_permissions" ("action", "description", "id", "module_id") values ('update', 'Customer 360 â€” update', 3, 1);
insert into "rbac_permissions" ("action", "description", "id", "module_id") values ('delete', 'Customer 360 â€” delete', 4, 1);
insert into "rbac_permissions" ("action", "description", "id", "module_id") values ('export', 'Customer 360 â€” export', 5, 1);
insert into "rbac_permissions" ("action", "description", "id", "module_id") values ('import', 'Customer 360 â€” import', 6, 1);
insert into "rbac_permissions" ("action", "description", "id", "module_id") values ('create', 'Dealer Network â€” create', 7, 2);
insert into "rbac_permissions" ("action", "description", "id", "module_id") values ('read', 'Dealer Network â€” read', 8, 2);
insert into "rbac_permissions" ("action", "description", "id", "module_id") values ('update', 'Dealer Network â€” update', 9, 2);
insert into "rbac_permissions" ("action", "description", "id", "module_id") values ('delete', 'Dealer Network â€” delete', 10, 2);
insert into "rbac_permissions" ("action", "description", "id", "module_id") values ('export', 'Dealer Network â€” export', 11, 2);
insert into "rbac_permissions" ("action", "description", "id", "module_id") values ('import', 'Dealer Network â€” import', 12, 2);
insert into "rbac_permissions" ("action", "description", "id", "module_id") values ('create', 'Identity Resolution â€” create', 13, 3);
insert into "rbac_permissions" ("action", "description", "id", "module_id") values ('read', 'Identity Resolution â€” read', 14, 3);
insert into "rbac_permissions" ("action", "description", "id", "module_id") values ('update', 'Identity Resolution â€” update', 15, 3);
insert into "rbac_permissions" ("action", "description", "id", "module_id") values ('delete', 'Identity Resolution â€” delete', 16, 3);
insert into "rbac_permissions" ("action", "description", "id", "module_id") values ('export', 'Identity Resolution â€” export', 17, 3);
insert into "rbac_permissions" ("action", "description", "id", "module_id") values ('import', 'Identity Resolution â€” import', 18, 3);
insert into "rbac_permissions" ("action", "description", "id", "module_id") values ('create', 'Segments â€” create', 19, 4);
insert into "rbac_permissions" ("action", "description", "id", "module_id") values ('read', 'Segments â€” read', 20, 4);
insert into "rbac_permissions" ("action", "description", "id", "module_id") values ('update', 'Segments â€” update', 21, 4);
insert into "rbac_permissions" ("action", "description", "id", "module_id") values ('delete', 'Segments â€” delete', 22, 4);
insert into "rbac_permissions" ("action", "description", "id", "module_id") values ('export', 'Segments â€” export', 23, 4);
insert into "rbac_permissions" ("action", "description", "id", "module_id") values ('import', 'Segments â€” import', 24, 4);
insert into "rbac_permissions" ("action", "description", "id", "module_id") values ('create', 'Behavioral Analytics â€” create', 25, 5);
insert into "rbac_permissions" ("action", "description", "id", "module_id") values ('read', 'Behavioral Analytics â€” read', 26, 5);
insert into "rbac_permissions" ("action", "description", "id", "module_id") values ('update', 'Behavioral Analytics â€” update', 27, 5);
insert into "rbac_permissions" ("action", "description", "id", "module_id") values ('delete', 'Behavioral Analytics â€” delete', 28, 5);
insert into "rbac_permissions" ("action", "description", "id", "module_id") values ('export', 'Behavioral Analytics â€” export', 29, 5);
insert into "rbac_permissions" ("action", "description", "id", "module_id") values ('import', 'Behavioral Analytics â€” import', 30, 5);
insert into "rbac_permissions" ("action", "description", "id", "module_id") values ('create', 'Promotional Effectiveness â€” create', 31, 6);
insert into "rbac_permissions" ("action", "description", "id", "module_id") values ('read', 'Promotional Effectiveness â€” read', 32, 6);
insert into "rbac_permissions" ("action", "description", "id", "module_id") values ('update', 'Promotional Effectiveness â€” update', 33, 6);
insert into "rbac_permissions" ("action", "description", "id", "module_id") values ('delete', 'Promotional Effectiveness â€” delete', 34, 6);
insert into "rbac_permissions" ("action", "description", "id", "module_id") values ('export', 'Promotional Effectiveness â€” export', 35, 6);
insert into "rbac_permissions" ("action", "description", "id", "module_id") values ('import', 'Promotional Effectiveness â€” import', 36, 6);
insert into "rbac_permissions" ("action", "description", "id", "module_id") values ('create', 'Consent & Compliance â€” create', 37, 7);
insert into "rbac_permissions" ("action", "description", "id", "module_id") values ('read', 'Consent & Compliance â€” read', 38, 7);
insert into "rbac_permissions" ("action", "description", "id", "module_id") values ('update', 'Consent & Compliance â€” update', 39, 7);
insert into "rbac_permissions" ("action", "description", "id", "module_id") values ('delete', 'Consent & Compliance â€” delete', 40, 7);
insert into "rbac_permissions" ("action", "description", "id", "module_id") values ('export', 'Consent & Compliance â€” export', 41, 7);
insert into "rbac_permissions" ("action", "description", "id", "module_id") values ('import', 'Consent & Compliance â€” import', 42, 7);
insert into "rbac_permissions" ("action", "description", "id", "module_id") values ('create', 'Access Management â€” create', 43, 8);
insert into "rbac_permissions" ("action", "description", "id", "module_id") values ('read', 'Access Management â€” read', 44, 8);
insert into "rbac_permissions" ("action", "description", "id", "module_id") values ('update', 'Access Management â€” update', 45, 8);
insert into "rbac_permissions" ("action", "description", "id", "module_id") values ('delete', 'Access Management â€” delete', 46, 8);
insert into "rbac_permissions" ("action", "description", "id", "module_id") values ('export', 'Access Management â€” export', 47, 8);
insert into "rbac_permissions" ("action", "description", "id", "module_id") values ('import', 'Access Management â€” import', 48, 8);
insert into "rbac_permissions" ("action", "description", "id", "module_id") values ('create', 'Data Model & Uploads â€” create', 49, 9);
insert into "rbac_permissions" ("action", "description", "id", "module_id") values ('read', 'Data Model & Uploads â€” read', 50, 9);
insert into "rbac_permissions" ("action", "description", "id", "module_id") values ('update', 'Data Model & Uploads â€” update', 51, 9);
insert into "rbac_permissions" ("action", "description", "id", "module_id") values ('delete', 'Data Model & Uploads â€” delete', 52, 9);
insert into "rbac_permissions" ("action", "description", "id", "module_id") values ('export', 'Data Model & Uploads â€” export', 53, 9);
insert into "rbac_permissions" ("action", "description", "id", "module_id") values ('import', 'Data Model & Uploads â€” import', 54, 9);
insert into "rbac_permissions" ("action", "description", "id", "module_id") values ('create', 'rtes — create', 55, 10);
insert into "rbac_permissions" ("action", "description", "id", "module_id") values ('read', 'rtes — read', 56, 10);
insert into "rbac_permissions" ("action", "description", "id", "module_id") values ('update', 'rtes — update', 57, 10);
insert into "rbac_permissions" ("action", "description", "id", "module_id") values ('delete', 'rtes — delete', 58, 10);
insert into "rbac_permissions" ("action", "description", "id", "module_id") values ('import', 'rtes — import', 59, 10);
insert into "rbac_permissions" ("action", "description", "id", "module_id") values ('export', 'rtes — export', 60, 10);
